### ISSUE TITLE
Return 9005 Invalid Parameter Name on non-existing parameters

### ISSUE THREAD

**Issue by adamhassel** [localhots/SimulaTR69#10]
The sim doesn't return a fault if a GPV is performed on a non-existing parameter value. Instead, it simply returns a parameter list omitting the non-existent parameters. This causes issues with e.g. AVSystem UMP, which relies on these faults for e.g. device classification.

Observed UMP behavior of batched GPV calls is:

1. Send a batch GPV
2. If one or more values in the list is not present in CPE data model, CPE returns 9005, but that 9005 does not contain information about which value was invalid
    * Instead, send one single GPV for each entry in list to get all that have values
3. If no fault, accept returned list of values.

**Comment by localhots** [comment]
Makes sense and the spec is clear about it too.
